[11-Apr-2023 17:13:51 Asia/Calcutta] Uncaught exception: 'ErrorException' with message 'Undefined variable $rows'
Stack trace: #0 /var/www/phpexam.com/html/App/Views/Feed/viewApp.php(36): Core\Error::errorHandler()
#1 /var/www/phpexam.com/html/Core/View.php(28): require('...')
#2 /var/www/phpexam.com/html/App/Controllers/Feed.php(71): Core\View::render()
#3 [internal function]: App\Controllers\Feed->appAction()
#4 /var/www/phpexam.com/html/Core/Controller.php(49): call_user_func_array()
#5 /var/www/phpexam.com/html/Core/Router.php(125): Core\Controller->__call()
#6 /var/www/phpexam.com/html/public/index.php(40): Core\Router->dispatch()
#7 {main}
Thrown in '/var/www/phpexam.com/html/App/Views/Feed/viewApp.php' on line 36
[11-Apr-2023 17:15:56 Asia/Calcutta] Uncaught exception: 'ErrorException' with message 'Undefined array key "fullname"'
Stack trace: #0 /var/www/phpexam.com/html/App/Views/Userprofile/new.php(28): Core\Error::errorHandler()
#1 /var/www/phpexam.com/html/Core/View.php(28): require('...')
#2 /var/www/phpexam.com/html/App/Controllers/Userprofile.php(33): Core\View::render()
#3 [internal function]: App\Controllers\Userprofile->createAction()
#4 /var/www/phpexam.com/html/Core/Controller.php(49): call_user_func_array()
#5 /var/www/phpexam.com/html/Core/Router.php(125): Core\Controller->__call()
#6 /var/www/phpexam.com/html/public/index.php(40): Core\Router->dispatch()
#7 {main}
Thrown in '/var/www/phpexam.com/html/App/Views/Userprofile/new.php' on line 28
[11-Apr-2023 17:16:00 Asia/Calcutta] Uncaught exception: 'ErrorException' with message 'Undefined variable $rows'
Stack trace: #0 /var/www/phpexam.com/html/App/Views/Feed/viewApp.php(36): Core\Error::errorHandler()
#1 /var/www/phpexam.com/html/Core/View.php(28): require('...')
#2 /var/www/phpexam.com/html/App/Controllers/Feed.php(71): Core\View::render()
#3 [internal function]: App\Controllers\Feed->appAction()
#4 /var/www/phpexam.com/html/Core/Controller.php(49): call_user_func_array()
#5 /var/www/phpexam.com/html/Core/Router.php(125): Core\Controller->__call()
#6 /var/www/phpexam.com/html/public/index.php(40): Core\Router->dispatch()
#7 {main}
Thrown in '/var/www/phpexam.com/html/App/Views/Feed/viewApp.php' on line 36
